---
engines:
  eslint:
    enabled: true
    configuration_file: eslint.config.mjs
    exclude_patterns:
      - '@typescript-eslint/no-unsafe-assignment'
      - '@typescript-eslint/no-unsafe-call'
      - '@typescript-eslint/no-unsafe-member-access'
      - '@typescript-eslint/no-unsafe-return'
      - '@typescript-eslint/no-unsafe-argument'
exclude_paths:
  - 'src/**/*.test.ts'
  - 'src/**/*.mock.ts'
  - '**/__tests__/**'
  - 'src/**/*migration*.ts'
  - 'src/**/migrations/**'
  - 'dist/**'
  - 'build/**'
  - 'coverage/**'
  - 'node_modules/**'
  - '*.config.js'
  - '*.config.mjs'
  - '*.config.ts'
  - src/data/seed.ts
